### ISSUE TITLE
Record only when cursor moves or frame differs

### ISSUE THREAD

**Issue by hinell** [Enselic/recordmydesktop#34]
Add a flag optimization to record conditionally:
* when cursor moves
* when frame changes (e.g. some pixeles change color)

I think this shouldn't be hard to implement.

### Benefits
It will have drammatic impact on resources usage (i.e. storage space and cpu) and keep it at very low level.

**Comment by Enselic** [comment]
Thank you for filing an issue and for your idea. I just committed a note to README.md that redirects contributions towards https://github.com/recordmydesktop/recordmydesktop which is a better base for new development of this tool.

**Comment by hinell** [comment]
Should I reopen the issue again over there? 

I would rather open a discussion instead... but there the "discussions" tab is disabled.
