### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by pmead7399** [Enselic/recordmydesktop#40]
You say  

"Search
in the code for
``
TODO: Port to GTK 3"`

Excuse my noob ignorance but search where please? 

TODO  just brings me here but I don't see a port to gtk 3

**Comment by Enselic** [comment]
I meant to "search in the code": https://github.com/search?q=repo%3AEnselic%2Frecordmydesktop%20TODO%3A%20Port%20to%20GTK%203&type=code

There is no port to GTK 3. That's on the TODO.
