### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [Enselic/recordmydesktop#44]
Dear @Enselic,

It will be nice to remove old parts like:
- https://sourceforge.net/p/recordmydesktop/mailman/
- https://sourceforge.net/p/recordmydesktop/_list/tickets
- https://sourceforge.net/p/recordmydesktop/bugs/
- https://sourceforge.net/p/recordmydesktop/support-requests/
- https://sourceforge.net/p/recordmydesktop/patches/
- https://sourceforge.net/p/recordmydesktop/feature-requests/
- https://sourceforge.net/p/recordmydesktop/discussion/
- https://sourceforge.net/p/recordmydesktop/svn/
- https://sourceforge.net/p/recordmydesktop/cvs/

Can you add a "move" box like https://sourceforge.net/projects/mumble for example.
- https://sourceforge.net/p/recordmydesktop/

To disable/delete tabs, go here: https://sourceforge.net/projects/recordmydesktop/
To add a new tab, go here: https://sourceforge.net/projects/recordmydesktop/
To change informations, go here: https://sourceforge.net/p/recordmydesktop/admin/overview
To export, go here: https://sourceforge.net/p/recordmydesktop/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/recordmydesktop/admin/overview
- A new tab, go here: https://sourceforge.net/projects/recordmydesktop/

Thanks in advance.

**Comment by Enselic** [comment]
Hi @Neustradamus and thank you for the proposal. The main project page https://sourceforge.net/projects/recordmydesktop/ says that the project has moved to GitHub. I wish I made that more visible, as it can be easy to miss.

But I am afraid I am not willing to put more time into maintaining an abandoned page, so I will close this as "won't fix".
